### ISSUE TITLE
When the code will be released ? 

### ISSUE THREAD

**Issue by AxeldeRomblay** [rsheth80/pmf-automl#1]
Hello, 

I have seen your paper at NeurIPS 2018 and I found it very interesting since the approach is original ! I am also developing an automated package (https://github.com/AxeldeRomblay/MLBox) which is slightly different (I guess mine focuses more on practical use-cases and less on hyperparameters tuning). Also, I have two questions on your approach : 

- how do you update your matrix factorization if you have a new pipeline configuration to integrate ? The same if you have new datasets and you want to "refit" the factorization ? 

- Is the factorization method robust if you try different metrics ? (AUC, f1-score, etc for classification or MSE, MAE, ... for regression)

Looking forward to see the code and play with it ! Thanks again. 
Axel

**Comment by rsheth80** [comment]
Sorry for the delay in posting!
